-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 21:40:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`eMail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eMail` (
  `eMail_ID` INT NOT NULL,
  `eMail` VARCHAR(100) NULL,
  PRIMARY KEY (`eMail_ID`),
  UNIQUE INDEX `eMail_UNIQUE` (`eMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phoneNumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phoneNumber` (
  `phoneNumber_ID` INT NOT NULL,
  `phoneNumber` INT NULL,
  PRIMARY KEY (`phoneNumber_ID`),
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `contact_ID` INT NOT NULL,
  `firstName` VARCHAR(100) NULL,
  `middleName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `countryCode` INT NULL,
  `birthDate` DATE NULL,
  `comments` VARCHAR(3000) NULL,
  `eMail_ID` INT NOT NULL,
  `phoneNumber_ID` INT NOT NULL,
  PRIMARY KEY (`contact_ID`, `eMail_ID`, `phoneNumber_ID`),
  UNIQUE INDEX `contact_ID_UNIQUE` (`contact_ID` ASC) VISIBLE,
  INDEX `fk_contact_eMail_idx` (`eMail_ID` ASC) VISIBLE,
  INDEX `fk_contact_phoneNumber1_idx` (`phoneNumber_ID` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_ID_UNIQUE` (`phoneNumber_ID` ASC) VISIBLE,
  UNIQUE INDEX `eMail_ID_UNIQUE` (`eMail_ID` ASC) VISIBLE,
  CONSTRAINT `fk_contact_eMail`
    FOREIGN KEY (`eMail_ID`)
    REFERENCES `mydb`.`eMail` (`eMail_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_phoneNumber1`
    FOREIGN KEY (`phoneNumber_ID`)
    REFERENCES `mydb`.`phoneNumber` (`phoneNumber_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
